# Generated by Django 5.0.3 on 2024-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaborateAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='auth_provider',
            field=models.CharField(default='Email', max_length=10),
        ),
    ]
