# Generated by Django 5.0.3 on 2024-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaborateAPIApp', '0002_individualprofile_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
