# Generated by Django 5.0.3 on 2024-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaborateAPIApp', '0003_alter_individualprofile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='auth_provider',
            field=models.CharField(choices=[('Email', 'Email'), ('Google', 'Google')], default='Email', max_length=10),
        ),
    ]
